### ISSUE TITLE
Newest Swift Syntax

### ISSUE THREAD

**Issue by dwicke01** [dropbox/PhotoWatch#2]
This project is not building for me in Xcode 7.1

**Comment by comiclandapp** [comment]
client.filesListFolder... value of DropboxClient has no member fileListFolder

**Comment by Thunor** [comment]
I was hoping this would show the correct usage of the download method.  Do you have a project working with the latest SwiftyDropBox as an example?  Neither this example or the tutorial work.  Thanks.

**Comment by greg-db** [comment]
@dwicke01 The latest version should be working in Xcode 7.1 and 7.2 now. Let us know if you're still seeing any issues.

@HerrDoktorBD It sounds like you're looking for `client.files.listFolder`, not `client.filesListFolder`.

@Thunor This sample should be working now, and the [tutorial](https://www.dropbox.com/developers/documentation/swift#tutorial) should also show the right usage now.
