### ISSUE TITLE
Dropbox login page

### ISSUE THREAD

**Issue by RegisStGelais** [dropbox/PhotoWatch#5]
I am trying the PhotoWatch demo app on my iPad mini and the dropbox login page does not display the captcha so I can't log in

![IMG_0376](https://user-images.githubusercontent.com/13238996/89832902-0fe70b80-db2e-11ea-88bc-36d4a95fe61f.PNG)

**Comment by greg-db** [comment]
I see you also posted this and followed up in the SwiftyDropbox repo, so I'll close this one in favor of that and follow up with you there: https://github.com/dropbox/SwiftyDropbox/issues/284
